package VistasCliente;

import Controladores.ControladorCliente;
import Modelo.Cliente;

import javax.swing.*;

public class FormularioCliente extends javax.swing.JFrame {

    private Cliente cliente;
    private ControladorCliente controladorCliente;

    public FormularioCliente(Cliente cliente, ControladorCliente controladorCliente) {
        initComponents();
        this.cliente = cliente;
        this.controladorCliente = controladorCliente;

        SelectSex.removeAllItems();
        SelectSex.addItem("Femenino");
        SelectSex.addItem("Masculino");
        SelectSex.addItem("Otro");

        if (cliente != null) {
            cargarDatosCliente();  // Si el cliente no es nulo, cargamos los datos para editar
        }

        GuardarBoton.addActionListener(e -> guardarCliente());
        CancelarBoton.addActionListener(e -> dispose()); // Cierra el formulario sin guardar
    }

    private void cargarDatosCliente() {
        TFCodigo.setText(String.valueOf(cliente.getCodigo()));
        TFNmbres.setText(cliente.getNombres());
        TFApllidos.setText(cliente.getApellidos());
        TFDireccion.setText(cliente.getDireccion());
        SelectSex.setSelectedItem(cliente.getSexo()); // Selecciona el valor en el JComboBox
        TFCorreo.setText(cliente.getCorreo());
        TFCelular.setText(cliente.getCelular());
        TFCodigo.setEditable(false);
    }

    private void guardarCliente() {
        if (!validarCampos()) {
            return;  // Si la validación falla, no continúa con el guardado
        }

        String nombres = TFNmbres.getText().trim();
        String apellidos = TFApllidos.getText().trim();
        String direccion = TFDireccion.getText().trim();
        String sexo = SelectSex.getSelectedItem().toString();
        String correo = TFCorreo.getText().trim();
        String celular = TFCelular.getText().trim();

        if (cliente == null) {
            cliente = new Cliente(0, nombres, apellidos, direccion,  sexo.charAt(0),  correo, celular);
            controladorCliente.agregarCliente(cliente);
            JOptionPane.showMessageDialog(this, "Cliente agregado exitosamente.");
        } else {
            cliente.setNombres(nombres);
            cliente.setApellidos(apellidos);
            cliente.setDireccion(direccion);
            cliente.setSexo(sexo.charAt(0));
            cliente.setCorreo(correo);
            cliente.setCelular(celular);
            controladorCliente.actualizarCliente(cliente);
            JOptionPane.showMessageDialog(this, "Cliente actualizado exitosamente.");
        }
        dispose(); 
    }

    private boolean validarCampos() {
        if (TFNmbres.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El nombre es obligatorio.");
            return false;
        }
        if (TFApllidos.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El apellido es obligatorio.");
            return false;
        }
        if (TFCorreo.getText().trim().isEmpty() || !TFCorreo.getText().contains("@")) {
            JOptionPane.showMessageDialog(this, "Ingrese un correo válido.");
            return false;
        }
        if (TFCelular.getText().trim().isEmpty() || !TFCelular.getText().matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "El celular debe contener solo números.");
            return false;
        }
        return true;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LTitulo = new javax.swing.JLabel();
        LCodigo = new javax.swing.JLabel();
        LnOMBRE = new javax.swing.JLabel();
        LApell = new javax.swing.JLabel();
        LDir = new javax.swing.JLabel();
        LSex = new javax.swing.JLabel();
        LCorreo = new javax.swing.JLabel();
        LCelular = new javax.swing.JLabel();
        TFCodigo = new javax.swing.JTextField();
        TFNmbres = new javax.swing.JTextField();
        TFApllidos = new javax.swing.JTextField();
        TFDireccion = new javax.swing.JTextField();
        TFCorreo = new javax.swing.JTextField();
        TFCelular = new javax.swing.JTextField();
        CancelarBoton = new javax.swing.JButton();
        GuardarBoton = new javax.swing.JButton();
        SelectSex = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LTitulo.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        LTitulo.setText("FORMULARIO CLIENTE");

        LCodigo.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        LCodigo.setText("Código:");

        LnOMBRE.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        LnOMBRE.setText("Nombres:");

        LApell.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        LApell.setText("Apellidos:");

        LDir.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        LDir.setText("Dirección:");

        LSex.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        LSex.setText("Sexo:");

        LCorreo.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        LCorreo.setText("Correo:");

        LCelular.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        LCelular.setText("Celular:");

        TFCodigo.setBackground(new java.awt.Color(0, 0, 0));
        TFCodigo.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        TFCodigo.setForeground(new java.awt.Color(255, 255, 255));
        TFCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFCodigoActionPerformed(evt);
            }
        });

        TFNmbres.setBackground(new java.awt.Color(0, 0, 0));
        TFNmbres.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        TFNmbres.setForeground(new java.awt.Color(255, 255, 255));

        TFApllidos.setBackground(new java.awt.Color(0, 0, 0));
        TFApllidos.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        TFApllidos.setForeground(new java.awt.Color(255, 255, 255));

        TFDireccion.setBackground(new java.awt.Color(0, 0, 0));
        TFDireccion.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        TFDireccion.setForeground(new java.awt.Color(255, 255, 255));

        TFCorreo.setBackground(new java.awt.Color(0, 0, 0));
        TFCorreo.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        TFCorreo.setForeground(new java.awt.Color(255, 255, 255));

        TFCelular.setBackground(new java.awt.Color(0, 0, 0));
        TFCelular.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        TFCelular.setForeground(new java.awt.Color(255, 255, 255));

        CancelarBoton.setBackground(new java.awt.Color(255, 0, 51));
        CancelarBoton.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        CancelarBoton.setText("Cancelar");

        GuardarBoton.setBackground(new java.awt.Color(60, 209, 113));
        GuardarBoton.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        GuardarBoton.setForeground(new java.awt.Color(60, 60, 60));
        GuardarBoton.setText("Guardar");

        SelectSex.setBackground(new java.awt.Color(0, 0, 0));
        SelectSex.setForeground(new java.awt.Color(255, 255, 255));
        SelectSex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(CancelarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(GuardarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LnOMBRE)
                            .addComponent(LApell)
                            .addComponent(LDir)
                            .addComponent(LSex)
                            .addComponent(LCorreo)
                            .addComponent(LCelular))
                        .addGap(129, 129, 129)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TFDireccion, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TFCorreo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TFCelular, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TFNmbres)
                            .addComponent(TFApllidos)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(TFCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(SelectSex, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(LTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LCodigo)
                    .addComponent(TFCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LnOMBRE)
                    .addComponent(TFNmbres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LApell)
                    .addComponent(TFApllidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LDir)
                    .addComponent(TFDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LSex)
                    .addComponent(SelectSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LCorreo)
                    .addComponent(TFCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LCelular)
                    .addComponent(TFCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelarBoton)
                    .addComponent(GuardarBoton))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TFCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFCodigoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelarBoton;
    private javax.swing.JButton GuardarBoton;
    private javax.swing.JLabel LApell;
    private javax.swing.JLabel LCelular;
    private javax.swing.JLabel LCodigo;
    private javax.swing.JLabel LCorreo;
    private javax.swing.JLabel LDir;
    private javax.swing.JLabel LSex;
    private javax.swing.JLabel LTitulo;
    private javax.swing.JLabel LnOMBRE;
    private javax.swing.JComboBox<String> SelectSex;
    private javax.swing.JTextField TFApllidos;
    private javax.swing.JTextField TFCelular;
    private javax.swing.JTextField TFCodigo;
    private javax.swing.JTextField TFCorreo;
    private javax.swing.JTextField TFDireccion;
    private javax.swing.JTextField TFNmbres;
    // End of variables declaration//GEN-END:variables
}
