package VistasCliente;
import Controladores.ControladorCliente;
import Modelo.Cliente;
import Modelo.ClienteTabla;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import VistasMain.VistaMenuPrincipal;



public class VistaCliente extends javax.swing.JFrame {
    
    private ControladorCliente controladorCliente;
    private ClienteTabla modeloTabla;
    private VistaMenuPrincipal menuPrincipal;
    
    // Constructor que acepta el menú principal
    public VistaCliente(VistaMenuPrincipal menuPrincipal) {
        this.menuPrincipal = menuPrincipal;
        initComponents();
        controladorCliente = new ControladorCliente();

        // Configurar modelo de tabla
        modeloTabla = new ClienteTabla(controladorCliente.obtenerTodosLosClientes());
        jTable1.setModel(modeloTabla);
        cargarClientes();

        // Configurar renderizadores y editores de botones para Editar y Eliminar
        configurarBotones();

        // Configurar botón Agregar
        AgregarBoton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                abrirFormularioCliente(null); // Abrir en modo agregar
            }
        });

        // Configurar botón Buscar
        BuscarBoton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                buscarCliente();
            }
        });
    }


    // Método para regresar al menú principal
    private void regresarAlMenuPrincipal() {
        menuPrincipal.setVisible(true);
        this.dispose();
    }


    private void cargarClientes() {
        List<Cliente> listaClientes = controladorCliente.obtenerTodosLosClientes();
        modeloTabla.setClientes(listaClientes); // Actualizar modelo de tabla
        jTable1.setModel(modeloTabla);   // Asociar modelo a la tabla
        configurarBotones(); // Configurar botones para nuevas filas
    }

    private void abrirFormularioCliente(Cliente cliente) {
        FormularioCliente formulario = new FormularioCliente(cliente, controladorCliente);
        formulario.setVisible(true);

        // Agrega un listener para detectar cuando el formulario se cierre
        formulario.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                cargarClientes();  // Recargar la tabla después de cerrar el formulario
            }
        });
    }


    private void buscarCliente() {
        String criterio = TFBuscar.getText().trim();
        List<Cliente> clientes = controladorCliente.buscarClientesPorCriterio(criterio);

        if (!clientes.isEmpty()) {
            modeloTabla.setClientes(clientes);
            jTable1.setModel(modeloTabla);
        } else {
            JOptionPane.showMessageDialog(this, "No se encontraron clientes.");
            cargarClientes(); // Recargar todos los clientes si no se encuentra ninguno
        }
    }


    private void configurarBotones() {
        jTable1.getColumn("Editar").setCellRenderer(new ButtonRenderer("Editar"));
        jTable1.getColumn("Editar").setCellEditor(new ButtonEditor(jTable1, "Editar"));
        jTable1.getColumn("Eliminar").setCellRenderer(new ButtonRenderer("Eliminar"));
        jTable1.getColumn("Eliminar").setCellEditor(new ButtonEditor(jTable1, "Eliminar"));
    }

    public void editarCliente(int row) {
        Cliente cliente = modeloTabla.getClienteAt(row);
        abrirFormularioCliente(cliente);
    }

    public void eliminarCliente(int row) {
        Cliente cliente = modeloTabla.getClienteAt(row);
        int confirmacion = JOptionPane.showConfirmDialog(this, "¿Está seguro de que desea eliminar este cliente?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION);
        if (confirmacion == JOptionPane.YES_OPTION) {
            controladorCliente.eliminarCliente(cliente.getCodigo());  // Pasar solo el código
            cargarClientes(); // Recargar la tabla después de eliminar
        }
    }


   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AgregarBoton = new javax.swing.JButton();
        TFBuscar = new javax.swing.JTextField();
        BuscarBoton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ButtonVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AgregarBoton.setBackground(new java.awt.Color(51, 255, 0));
        AgregarBoton.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        AgregarBoton.setText("Agregar Nuevo Cliente");

        TFBuscar.setBackground(new java.awt.Color(0, 0, 0));
        TFBuscar.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        TFBuscar.setForeground(new java.awt.Color(255, 255, 255));

        BuscarBoton.setBackground(new java.awt.Color(0, 0, 204));
        BuscarBoton.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        BuscarBoton.setForeground(new java.awt.Color(255, 255, 255));
        BuscarBoton.setText("Buscar");

        jTable1.setBackground(new java.awt.Color(51, 47, 38));
        jTable1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTable1.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9"
            }
        ));
        jTable1.setInheritsPopupMenu(true);
        jTable1.setMaximumSize(new java.awt.Dimension(2147483647, 120));
        jTable1.setMinimumSize(new java.awt.Dimension(180, 120));
        jTable1.setRowHeight(30);
        jScrollPane1.setViewportView(jTable1);

        ButtonVolver.setBackground(new java.awt.Color(255, 0, 255));
        ButtonVolver.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        ButtonVolver.setText("Regresar al Menú");
        ButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TFBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BuscarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(AgregarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 962, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(372, 372, 372)
                        .addComponent(ButtonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AgregarBoton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BuscarBoton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(ButtonVolver)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonVolverActionPerformed
        regresarAlMenuPrincipal();
    }//GEN-LAST:event_ButtonVolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarBoton;
    private javax.swing.JButton BuscarBoton;
    private javax.swing.JButton ButtonVolver;
    private javax.swing.JTextField TFBuscar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
