
package VistasMain;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import VistasCliente.VistaCliente;
import VistasPlanMantenimiento.VistaPlanMantenimiento;
import VistasTecnico.VistaTecnico;
import VistasVehiculo.VistaVehiculo;

public class VistaMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaMenuPrincipal
     */
    public VistaMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LTITLE = new javax.swing.JLabel();
        buttonvehiculos = new javax.swing.JButton();
        buttonclientes = new javax.swing.JButton();
        buttontecnico = new javax.swing.JButton();
        buttonplanes = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LTITLE.setFont(new java.awt.Font("Century Schoolbook L", 1, 45)); // NOI18N
        LTITLE.setForeground(new java.awt.Color(255, 255, 255));
        LTITLE.setText("MÓDULOS");
        getContentPane().add(LTITLE, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 13, -1, 64));

        buttonvehiculos.setBackground(new java.awt.Color(153, 153, 153));
        buttonvehiculos.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 15)); // NOI18N
        buttonvehiculos.setText("Módulo de Mantenimiento de vehiculos");
        buttonvehiculos.setActionCommand("Módulo de \nmantenimiento\nde vehiculos");
        buttonvehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonvehiculosActionPerformed(evt);
            }
        });
        getContentPane().add(buttonvehiculos, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 95, 350, 93));

        buttonclientes.setBackground(new java.awt.Color(153, 153, 153));
        buttonclientes.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 15)); // NOI18N
        buttonclientes.setText("Módulo de Clientes");
        buttonclientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonclientesActionPerformed(evt);
            }
        });
        getContentPane().add(buttonclientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 206, 350, 93));

        buttontecnico.setBackground(new java.awt.Color(153, 153, 153));
        buttontecnico.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 15)); // NOI18N
        buttontecnico.setText("Módulo de Mantenimiento del  Técnico");
        buttontecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttontecnicoActionPerformed(evt);
            }
        });
        getContentPane().add(buttontecnico, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 317, 350, 89));

        buttonplanes.setBackground(new java.awt.Color(153, 153, 153));
        buttonplanes.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 15)); // NOI18N
        buttonplanes.setText("Módulo de Plan de mantenimiento ");
        buttonplanes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonplanesActionPerformed(evt);
            }
        });
        getContentPane().add(buttonplanes, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 424, 350, 89));

        jButton5.setBackground(new java.awt.Color(255, 0, 0));
        jButton5.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Cerrar");
        jButton5.setToolTipText("");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 551, 191, 37));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setAutoscrolls(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonvehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonvehiculosActionPerformed
        new VistaVehiculo(this).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_buttonvehiculosActionPerformed

    private void buttonclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonclientesActionPerformed
        new VistaCliente(this).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_buttonclientesActionPerformed

    private void buttontecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttontecnicoActionPerformed
         new VistaTecnico(this).setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_buttontecnicoActionPerformed

    private void buttonplanesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonplanesActionPerformed
        new VistaPlanMantenimiento(this).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_buttonplanesActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "¿Estás seguro de que deseas salir?", "Confirmación", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            System.exit(0); // Cierra la aplicación
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LTITLE;
    private javax.swing.JButton buttonclientes;
    private javax.swing.JButton buttonplanes;
    private javax.swing.JButton buttontecnico;
    private javax.swing.JButton buttonvehiculos;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
