
package VistasMain;
import Controladores.ControladorUsuario;
import javax.swing.JOptionPane;

public class VistaLoginUsuario extends javax.swing.JFrame {

    public VistaLoginUsuario() {
        initComponents();
        // Añadir la funcionalidad de mostrar/ocultar contraseña
        CHECKBOXCONTRASENAVER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                if (CHECKBOXCONTRASENAVER.isSelected()) {
                    TFpassword.setEchoChar((char) 0); // Muestra la contraseña
                } else {
                    TFpassword.setEchoChar('*'); // Oculta la contraseña
                }
            }
        });
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lname = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TFpassword = new javax.swing.JPasswordField();
        TFUsuario = new javax.swing.JTextField();
        ButonReset = new javax.swing.JButton();
        CHECKBOXCONTRASENAVER = new javax.swing.JCheckBox();
        ButonLogin = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lname.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 25)); // NOI18N
        lname.setForeground(new java.awt.Color(255, 255, 255));
        lname.setText("INICIO DE SESIÓN");
        getContentPane().add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 23, -1, -1));

        jLabel1.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuario");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 108, -1, -1));

        jLabel2.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 168, -1, -1));

        TFpassword.setBackground(new java.awt.Color(204, 204, 204));
        TFpassword.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 13)); // NOI18N
        TFpassword.setForeground(new java.awt.Color(102, 102, 102));
        TFpassword.setText("jmedina26");
        TFpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFpasswordActionPerformed(evt);
            }
        });
        getContentPane().add(TFpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 164, 181, -1));

        TFUsuario.setBackground(new java.awt.Color(204, 204, 204));
        TFUsuario.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 13)); // NOI18N
        TFUsuario.setForeground(new java.awt.Color(102, 102, 102));
        getContentPane().add(TFUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 107, 181, -1));

        ButonReset.setBackground(new java.awt.Color(255, 51, 51));
        ButonReset.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        ButonReset.setText("Reset");
        ButonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButonResetActionPerformed(evt);
            }
        });
        getContentPane().add(ButonReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 271, 124, -1));

        CHECKBOXCONTRASENAVER.setBackground(new java.awt.Color(153, 153, 153));
        CHECKBOXCONTRASENAVER.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        CHECKBOXCONTRASENAVER.setForeground(new java.awt.Color(255, 255, 255));
        CHECKBOXCONTRASENAVER.setText("Mostrar contraseña");
        getContentPane().add(CHECKBOXCONTRASENAVER, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 206, -1, -1));

        ButonLogin.setBackground(new java.awt.Color(102, 255, 0));
        ButonLogin.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        ButonLogin.setText("Ingresar");
        ButonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButonLoginActionPerformed(evt);
            }
        });
        getContentPane().add(ButonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 270, 149, -1));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 450, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButonLoginActionPerformed
        String usuario = TFUsuario.getText();
        String contrasena = new String(TFpassword.getPassword());

        ControladorUsuario controlador = new ControladorUsuario();
        boolean autenticado = controlador.iniciarSesion(usuario, contrasena);

        if (autenticado) {
            JOptionPane.showMessageDialog(this, "Bienvenido!");
            new VistaMenuPrincipal().setVisible(true); // Abre el menú principal
            this.dispose(); // Cierra la ventana de login
        } else {
            JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ButonLoginActionPerformed

    private void ButonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButonResetActionPerformed
        TFUsuario.setText("");
        TFpassword.setText("");
        CHECKBOXCONTRASENAVER.setSelected(false);
        TFpassword.setEchoChar('*'); // As
    }//GEN-LAST:event_ButonResetActionPerformed

    private void TFpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFpasswordActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaLoginUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaLoginUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaLoginUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaLoginUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaLoginUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButonLogin;
    private javax.swing.JButton ButonReset;
    private javax.swing.JCheckBox CHECKBOXCONTRASENAVER;
    private javax.swing.JTextField TFUsuario;
    private javax.swing.JPasswordField TFpassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lname;
    // End of variables declaration//GEN-END:variables
}
