package VistasTecnico;


import Controladores.ControladorTecnico;
import Modelo.Tecnico;

import javax.swing.*;

public class FormularioTecnico extends javax.swing.JFrame {

    
    private Tecnico tecnico;
    private ControladorTecnico controladorTecnico;
    
    //Constructor
    public FormularioTecnico(Tecnico tecnico, ControladorTecnico controladorTecnico) {
        initComponents();
        this.tecnico = tecnico;
        this.controladorTecnico = controladorTecnico;

        // Agregar opciones al JComboBox SELECTSEX
        SELECTSEX.removeAllItems();
        SELECTSEX.addItem("Femenino");
        SELECTSEX.addItem("Masculino");
        SELECTSEX.addItem("Otro");

        if (tecnico != null) {
            cargarDatosTecnico();
        }

        GuardarBoton.addActionListener(e -> guardarTecnico());
        CancelarBoton.addActionListener(e -> dispose());
    }

    private void cargarDatosTecnico() {
        TFCodigo.setText(String.valueOf(tecnico.getCodigo()));
        TFNombres.setText(tecnico.getNombres());
        TFApellidos.setText(tecnico.getApellidos());
        TFDireccion.setText(tecnico.getDireccion());
        SELECTSEX.setSelectedItem(tecnico.getSexo()); // Selecciona el valor en el JComboBox
        TFCorreo.setText(tecnico.getCorreo());
        TFCelular.setText(tecnico.getCelular());
        TFEspecialidad.setText(tecnico.getEspecialidad());
        TFTiempoServicio.setText(String.valueOf(tecnico.getTiempoServicio()));

        TFCodigo.setEditable(false);
    }

    private void guardarTecnico() {
        try {
            String nombres = TFNombres.getText();
            String apellidos = TFApellidos.getText();
            String direccion = TFDireccion.getText();
            String sexo = SELECTSEX.getSelectedItem().toString(); // Obtener el valor completo seleccionado
            String correo = TFCorreo.getText();
            String celular = TFCelular.getText();
            String especialidad = TFEspecialidad.getText();
            int tiempoServicio = Integer.parseInt(TFTiempoServicio.getText());

            if (tecnico == null) {
                tecnico = new Tecnico(0, nombres, apellidos, direccion, sexo.charAt(0), correo, celular, especialidad, tiempoServicio);
                controladorTecnico.agregarTecnico(tecnico);
                JOptionPane.showMessageDialog(this, "Técnico agregado exitosamente.");
            } else {
                tecnico.setNombres(nombres);
                tecnico.setApellidos(apellidos);
                tecnico.setDireccion(direccion);
                tecnico.setSexo(sexo.charAt(0));
                tecnico.setCorreo(correo);
                tecnico.setCelular(celular);
                tecnico.setEspecialidad(especialidad);
                tecnico.setTiempoServicio(tiempoServicio);
                controladorTecnico.actualizarTecnico(tecnico);
                JOptionPane.showMessageDialog(this, "Técnico actualizado exitosamente.");
            }
            dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: Verifica los campos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LTitulo = new javax.swing.JLabel();
        LCodigo = new javax.swing.JLabel();
        LnOMBRE = new javax.swing.JLabel();
        LApell = new javax.swing.JLabel();
        LDir = new javax.swing.JLabel();
        LSex = new javax.swing.JLabel();
        LCorreo = new javax.swing.JLabel();
        LCelular = new javax.swing.JLabel();
        TFCodigo = new javax.swing.JTextField();
        TFNombres = new javax.swing.JTextField();
        TFApellidos = new javax.swing.JTextField();
        TFDireccion = new javax.swing.JTextField();
        TFCorreo = new javax.swing.JTextField();
        TFCelular = new javax.swing.JTextField();
        CancelarBoton = new javax.swing.JButton();
        GuardarBoton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        TFEspecialidad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TFTiempoServicio = new javax.swing.JTextField();
        SELECTSEX = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(52, 50, 55));

        LTitulo.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        LTitulo.setText("FORMULARIO TÉCNICO");

        LCodigo.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        LCodigo.setText("Código:");

        LnOMBRE.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        LnOMBRE.setText("Nombres:");

        LApell.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        LApell.setText("Apellidos:");

        LDir.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        LDir.setText("Dirección:");

        LSex.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        LSex.setText("Sexo:");

        LCorreo.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        LCorreo.setText("Correo:");

        LCelular.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        LCelular.setText("Celular");

        TFCodigo.setBackground(new java.awt.Color(0, 0, 0));
        TFCodigo.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        TFCodigo.setForeground(new java.awt.Color(255, 255, 255));
        TFCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFCodigoActionPerformed(evt);
            }
        });

        TFNombres.setBackground(new java.awt.Color(0, 0, 0));
        TFNombres.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        TFNombres.setForeground(new java.awt.Color(255, 255, 255));

        TFApellidos.setBackground(new java.awt.Color(0, 0, 0));
        TFApellidos.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        TFApellidos.setForeground(new java.awt.Color(255, 255, 255));

        TFDireccion.setBackground(new java.awt.Color(0, 0, 0));
        TFDireccion.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        TFDireccion.setForeground(new java.awt.Color(255, 255, 255));

        TFCorreo.setBackground(new java.awt.Color(0, 0, 0));
        TFCorreo.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        TFCorreo.setForeground(new java.awt.Color(255, 255, 255));

        TFCelular.setBackground(new java.awt.Color(0, 0, 0));
        TFCelular.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        TFCelular.setForeground(new java.awt.Color(255, 255, 255));

        CancelarBoton.setBackground(new java.awt.Color(255, 51, 51));
        CancelarBoton.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        CancelarBoton.setText("Cancelar");

        GuardarBoton.setBackground(new java.awt.Color(51, 255, 0));
        GuardarBoton.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        GuardarBoton.setText("Guardar");

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        jLabel1.setText("Especialidad:");

        TFEspecialidad.setBackground(new java.awt.Color(0, 0, 0));
        TFEspecialidad.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        TFEspecialidad.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        jLabel2.setText("Tiempo de Servicio (años):");

        TFTiempoServicio.setBackground(new java.awt.Color(0, 0, 0));
        TFTiempoServicio.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        TFTiempoServicio.setForeground(new java.awt.Color(255, 255, 255));

        SELECTSEX.setBackground(new java.awt.Color(0, 0, 0));
        SELECTSEX.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        SELECTSEX.setForeground(new java.awt.Color(255, 255, 255));
        SELECTSEX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        SELECTSEX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SELECTSEXActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(CancelarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(GuardarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LnOMBRE)
                            .addComponent(LApell)
                            .addComponent(LDir)
                            .addComponent(LSex)
                            .addComponent(LCorreo)
                            .addComponent(LCelular)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TFDireccion)
                            .addComponent(TFCorreo)
                            .addComponent(TFCelular)
                            .addComponent(TFNombres, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TFApellidos, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TFEspecialidad)
                            .addComponent(TFTiempoServicio)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(TFCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(SELECTSEX, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(LTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LCodigo)
                    .addComponent(TFCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LnOMBRE)
                    .addComponent(TFNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LApell)
                    .addComponent(TFApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LDir)
                    .addComponent(TFDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LSex)
                    .addComponent(SELECTSEX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LCorreo)
                    .addComponent(TFCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LCelular)
                    .addComponent(TFCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TFEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TFTiempoServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelarBoton)
                    .addComponent(GuardarBoton))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TFCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFCodigoActionPerformed

    private void SELECTSEXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SELECTSEXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SELECTSEXActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelarBoton;
    private javax.swing.JButton GuardarBoton;
    private javax.swing.JLabel LApell;
    private javax.swing.JLabel LCelular;
    private javax.swing.JLabel LCodigo;
    private javax.swing.JLabel LCorreo;
    private javax.swing.JLabel LDir;
    private javax.swing.JLabel LSex;
    private javax.swing.JLabel LTitulo;
    private javax.swing.JLabel LnOMBRE;
    private javax.swing.JComboBox<String> SELECTSEX;
    private javax.swing.JTextField TFApellidos;
    private javax.swing.JTextField TFCelular;
    private javax.swing.JTextField TFCodigo;
    private javax.swing.JTextField TFCorreo;
    private javax.swing.JTextField TFDireccion;
    private javax.swing.JTextField TFEspecialidad;
    private javax.swing.JTextField TFNombres;
    private javax.swing.JTextField TFTiempoServicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
