package VistasTecnico;


import Controladores.ControladorTecnico;
import Modelo.Tecnico;
import Modelo.TecnicoTabla;
import VistasTecnico.ButtonEditor;
import VistasTecnico.ButtonRenderer;
import VistasMain.VistaMenuPrincipal;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;

public class VistaTecnico extends javax.swing.JFrame {

    private ControladorTecnico controladorTecnico;
    private TecnicoTabla modeloTabla;
    private VistaMenuPrincipal menuPrincipal;
    
    public VistaTecnico(VistaMenuPrincipal menuPrincipal) {
        this.menuPrincipal = menuPrincipal;
        controladorTecnico = new ControladorTecnico(); // Inicializar el controlador
        modeloTabla = new TecnicoTabla(new ArrayList<>()); // Inicializar modelo de tabla vacío
        initComponents();

        // Asigna el modelo inicial a la tabla
        jTable1.setModel(modeloTabla);

        // Cargar técnicos y configurar la tabla y los botones
        cargarTecnicos();
        configurarBotones();

        // Configurar botón "Agregar nuevo Técnico" para abrir el formulario
        AgregarBoton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                abrirFormularioTecnico(null); // Abrir en modo agregar
            }
        });

        // Configurar botón "Buscar"
        BuscarBoton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                buscarTecnico();
            }
        });
    }



    // Método para regresar al menú principal
    private void regresarAlMenuPrincipal() {
        menuPrincipal.setVisible(true);
        this.dispose();
    }

   
    private void cargarTecnicos() {
        List<Tecnico> listaTecnicos = controladorTecnico.obtenerTodosLosTecnicos();
        modeloTabla.setTecnicos(listaTecnicos); // Actualizar modelo de tabla
        jTable1.setModel(modeloTabla); // Asociar modelo a la tabla
        configurarBotones(); // Configurar botones para nuevas filas
    }

    private void abrirFormularioTecnico(Tecnico tecnico) {
        FormularioTecnico formulario = new FormularioTecnico(tecnico, controladorTecnico);
        
        formulario.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                cargarTecnicos();
            }
        });

        formulario.setVisible(true);
    }

    private void buscarTecnico() {
        String criterio = TFBuscar.getText().trim();
        List<Tecnico> tecnicos = controladorTecnico.buscarTecnicosPorCriterio(criterio);

        if (!tecnicos.isEmpty()) {
            modeloTabla.setTecnicos(tecnicos);
            jTable1.setModel(modeloTabla);
        } else {
            JOptionPane.showMessageDialog(this, "No se encontraron técnicos.");
            modeloTabla.setTecnicos(new ArrayList<>()); // Limpiar la tabla si no se encuentran resultados
            jTable1.setModel(modeloTabla);
        }
    }


    private void configurarBotones() {
        jTable1.getColumn("Editar").setCellRenderer(new ButtonRenderer("Editar"));
        jTable1.getColumn("Editar").setCellEditor(new ButtonEditor(jTable1, "Editar"));
        jTable1.getColumn("Eliminar").setCellRenderer(new ButtonRenderer("Eliminar"));
        jTable1.getColumn("Eliminar").setCellEditor(new ButtonEditor(jTable1, "Eliminar"));
    }

    public void editarTecnico(int row) {
        if (row >= 0) { // Verifica que la fila seleccionada sea válida
            Tecnico tecnico = modeloTabla.getTecnicoAt(row);
            abrirFormularioTecnico(tecnico);
            cargarTecnicos(); // Recargar después de editar
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un técnico para editar.");
        }
    }

    public void eliminarTecnico(int row) {
        Tecnico tecnico = modeloTabla.getTecnicoAt(row);
        int confirmacion = JOptionPane.showConfirmDialog(this, "¿Está seguro de que desea eliminar este técnico?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION);
        if (confirmacion == JOptionPane.YES_OPTION) {
            controladorTecnico.eliminarTecnico(tecnico.getCodigo());
            cargarTecnicos(); // Recargar la tabla después de eliminar
        }
    }


   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AgregarBoton = new javax.swing.JButton();
        TFBuscar = new javax.swing.JTextField();
        BuscarBoton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AgregarBoton.setBackground(new java.awt.Color(102, 255, 0));
        AgregarBoton.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        AgregarBoton.setText("Agregar nuevo Técnico");

        TFBuscar.setBackground(new java.awt.Color(0, 0, 0));
        TFBuscar.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        TFBuscar.setForeground(new java.awt.Color(255, 255, 255));

        BuscarBoton.setBackground(new java.awt.Color(0, 0, 204));
        BuscarBoton.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        BuscarBoton.setForeground(new java.awt.Color(255, 255, 255));
        BuscarBoton.setText("Buscar");

        jTable1.setBackground(new java.awt.Color(51, 47, 38));
        jTable1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTable1.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(51, 51, 51));
        jTable1.setMaximumSize(new java.awt.Dimension(2147483647, 120));
        jTable1.setMinimumSize(new java.awt.Dimension(180, 120));
        jTable1.setPreferredSize(new java.awt.Dimension(900, 120));
        jTable1.setRowHeight(30);
        jScrollPane1.setViewportView(jTable1);

        jButton1.setBackground(new java.awt.Color(204, 0, 204));
        jButton1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Volver al Menú");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TFBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BuscarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 962, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AgregarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(379, 379, 379)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AgregarBoton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BuscarBoton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButton1)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        regresarAlMenuPrincipal();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarBoton;
    private javax.swing.JButton BuscarBoton;
    private javax.swing.JTextField TFBuscar;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
