package VistasPlanMantenimiento;

import Modelo.Vehiculo;
import javax.swing.*;

public class VistaVehiculo extends javax.swing.JFrame {

   
    private JLabel valorCodigo;
    private JLabel valorPlaca;
    private JLabel valorNumeroSerie;
    private JLabel valorAnoFabricacion;
    private JLabel valorCantidadPuertas;
    private JLabel valorColor;
    private JLabel valorCilindrada;
    private JLabel valorDueno;

    
     public VistaVehiculo(Vehiculo vehiculo) {
        initComponents();
        cargarDatosVehiculo(vehiculo);
    }
    
     private void cargarDatosVehiculo(Vehiculo vehiculo) {
        TFCODIGO.setText(String.valueOf(vehiculo.getCodigo()));
        TFPLACA.setText(vehiculo.getPlaca());
        TFCODIGOSERIE.setText(vehiculo.getNumeroSerie());
        TFANHO.setText(String.valueOf(vehiculo.getAnhoFabricacion()));
        TFPUERTAS.setText(String.valueOf(vehiculo.getCantidadPuertas()));
        TFCOLOR.setText(vehiculo.getColor());
        TFCILINDRADA.setText(String.valueOf(vehiculo.getCilindrada()));
        TFDUENHO.setText(vehiculo.getDuenho());

        // Hacer los campos no editables
        TFCODIGO.setEditable(false);
        TFPLACA.setEditable(false);
        TFCODIGOSERIE.setEditable(false);
        TFANHO.setEditable(false);
        TFPUERTAS.setEditable(false);
        TFCOLOR.setEditable(false);
        TFCILINDRADA.setEditable(false);
        TFDUENHO.setEditable(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TFCODIGO = new javax.swing.JTextField();
        TFPLACA = new javax.swing.JTextField();
        TFCODIGOSERIE = new javax.swing.JTextField();
        TFANHO = new javax.swing.JTextField();
        TFPUERTAS = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TFCOLOR = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TFCILINDRADA = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TFDUENHO = new javax.swing.JTextField();
        BOTONCERRAR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 28)); // NOI18N
        jLabel1.setText("DATOS DEL VEHICULO: ");

        jLabel2.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 13)); // NOI18N
        jLabel2.setText("CODIGO");

        jLabel3.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 13)); // NOI18N
        jLabel3.setText("PLACA");

        jLabel4.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 13)); // NOI18N
        jLabel4.setText("NÚMERO DE SERIE");

        jLabel5.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 13)); // NOI18N
        jLabel5.setText("AÑO DE FABRICACIÓN");

        jLabel6.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 13)); // NOI18N
        jLabel6.setText("CANTIDAD DE PUERTAS");

        TFCODIGO.setBackground(new java.awt.Color(0, 0, 51));
        TFCODIGO.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        TFCODIGO.setForeground(new java.awt.Color(255, 255, 255));

        TFPLACA.setBackground(new java.awt.Color(0, 0, 51));
        TFPLACA.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        TFPLACA.setForeground(new java.awt.Color(255, 255, 255));

        TFCODIGOSERIE.setBackground(new java.awt.Color(0, 0, 51));
        TFCODIGOSERIE.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        TFCODIGOSERIE.setForeground(new java.awt.Color(255, 255, 255));

        TFANHO.setBackground(new java.awt.Color(0, 0, 51));
        TFANHO.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        TFANHO.setForeground(new java.awt.Color(255, 255, 255));

        TFPUERTAS.setBackground(new java.awt.Color(0, 0, 51));
        TFPUERTAS.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        TFPUERTAS.setForeground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 13)); // NOI18N
        jLabel7.setText("COLOR");

        TFCOLOR.setBackground(new java.awt.Color(0, 0, 51));
        TFCOLOR.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        TFCOLOR.setForeground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 13)); // NOI18N
        jLabel8.setText("CILINDRADA");

        TFCILINDRADA.setBackground(new java.awt.Color(0, 0, 51));
        TFCILINDRADA.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        TFCILINDRADA.setForeground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 13)); // NOI18N
        jLabel9.setText("DUEÑHO");

        TFDUENHO.setBackground(new java.awt.Color(0, 0, 51));
        TFDUENHO.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        TFDUENHO.setForeground(new java.awt.Color(255, 255, 255));

        BOTONCERRAR.setBackground(new java.awt.Color(167, 9, 9));
        BOTONCERRAR.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        BOTONCERRAR.setText("CERRAR");
        BOTONCERRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTONCERRARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(BOTONCERRAR, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jLabel5)
                                                .addGap(27, 27, 27))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel4)
                                                    .addComponent(jLabel6))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(TFCODIGOSERIE, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                                            .addComponent(TFCODIGO, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TFANHO)
                                            .addComponent(TFPUERTAS)))
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel7)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TFPLACA, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                                    .addComponent(TFCOLOR)
                                    .addComponent(TFCILINDRADA)
                                    .addComponent(TFDUENHO))))
                        .addGap(27, 27, 27))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TFCODIGO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(TFPLACA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TFCODIGOSERIE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(TFCOLOR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TFANHO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(TFCILINDRADA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TFPUERTAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(TFDUENHO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(BOTONCERRAR)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BOTONCERRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTONCERRARActionPerformed
        this.dispose();
    }//GEN-LAST:event_BOTONCERRARActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BOTONCERRAR;
    private javax.swing.JTextField TFANHO;
    private javax.swing.JTextField TFCILINDRADA;
    private javax.swing.JTextField TFCODIGO;
    private javax.swing.JTextField TFCODIGOSERIE;
    private javax.swing.JTextField TFCOLOR;
    private javax.swing.JTextField TFDUENHO;
    private javax.swing.JTextField TFPLACA;
    private javax.swing.JTextField TFPUERTAS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
