package VistasPlanMantenimiento;

import Modelo.Tecnico;
import javax.swing.*;

public class VistaTecnico extends javax.swing.JFrame {

   
    private JLabel valorCodigo;
    private JLabel valorNombres;
    private JLabel valorApellidos;
    private JLabel valorDireccion;
    private JLabel valorSexo;
    private JLabel valorCorreo;
    private JLabel valorCelular;
    private JLabel valorEspecialidad;
    private JLabel valorTiempoServicio;

    public VistaTecnico(Tecnico tecnico) {
        initComponents();
        cargarDatosTecnico(tecnico);
    }

    private void cargarDatosTecnico(Tecnico tecnico) {
        TFCODIGO.setText(String.valueOf(tecnico.getCodigo()));
        TFNOMBRES.setText(tecnico.getNombres());
        TFAPELLIDOS.setText(tecnico.getApellidos());
        TFDIRECCION.setText(tecnico.getDireccion());
         String sexoDescripcion;
        switch (tecnico.getSexo()) {
            case 'F':
                sexoDescripcion = "Femenino";
                break;
            case 'M':
                sexoDescripcion = "Masculino";
                break;
            case 'O':
                sexoDescripcion = "Otro";
                break;
            default:
                sexoDescripcion = "No especificado";
                break;
        }
        TFSEXO.setText(sexoDescripcion);
        TFCORREO.setText(tecnico.getCorreo());
        TFCELULAR.setText(tecnico.getCelular());
        TFESPECIALIDAD.setText(tecnico.getEspecialidad());
        TFTIEMPOSERVICIO.setText(String.valueOf(tecnico.getTiempoServicio()));

        // Hacer los campos no editables
        TFCODIGO.setEditable(false);
        TFNOMBRES.setEditable(false);
        TFAPELLIDOS.setEditable(false);
        TFDIRECCION.setEditable(false);
        TFSEXO.setEditable(false);
        TFCORREO.setEditable(false);
        TFCELULAR.setEditable(false);
        TFESPECIALIDAD.setEditable(false);
        TFTIEMPOSERVICIO.setEditable(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TFCODIGO = new javax.swing.JTextField();
        TFCELULAR = new javax.swing.JTextField();
        TFNOMBRES = new javax.swing.JTextField();
        TFDIRECCION = new javax.swing.JTextField();
        TFCORREO = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TFAPELLIDOS = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TFSEXO = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TFESPECIALIDAD = new javax.swing.JTextField();
        BOTONCERRAR = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        TFTIEMPOSERVICIO = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 28)); // NOI18N
        jLabel1.setText("DATOS DEL TÉCNICO: ");

        jLabel2.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 13)); // NOI18N
        jLabel2.setText("CODIGO");

        jLabel3.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 13)); // NOI18N
        jLabel3.setText("CELULAR");

        jLabel4.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 13)); // NOI18N
        jLabel4.setText("NOMBRES");

        jLabel5.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 13)); // NOI18N
        jLabel5.setText("DIRECCIÓN");

        jLabel6.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 13)); // NOI18N
        jLabel6.setText("CORREO");

        TFCODIGO.setBackground(new java.awt.Color(0, 0, 51));
        TFCODIGO.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        TFCODIGO.setForeground(new java.awt.Color(255, 255, 255));

        TFCELULAR.setBackground(new java.awt.Color(0, 0, 51));
        TFCELULAR.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        TFCELULAR.setForeground(new java.awt.Color(255, 255, 255));

        TFNOMBRES.setBackground(new java.awt.Color(0, 0, 51));
        TFNOMBRES.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        TFNOMBRES.setForeground(new java.awt.Color(255, 255, 255));

        TFDIRECCION.setBackground(new java.awt.Color(0, 0, 51));
        TFDIRECCION.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        TFDIRECCION.setForeground(new java.awt.Color(255, 255, 255));

        TFCORREO.setBackground(new java.awt.Color(0, 0, 51));
        TFCORREO.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        TFCORREO.setForeground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 13)); // NOI18N
        jLabel7.setText("APELLIDOS");

        TFAPELLIDOS.setBackground(new java.awt.Color(0, 0, 51));
        TFAPELLIDOS.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        TFAPELLIDOS.setForeground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 13)); // NOI18N
        jLabel8.setText("GÉNERO");

        TFSEXO.setBackground(new java.awt.Color(0, 0, 51));
        TFSEXO.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        TFSEXO.setForeground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 13)); // NOI18N
        jLabel9.setText("ESPECIALIDAD");

        TFESPECIALIDAD.setBackground(new java.awt.Color(0, 0, 51));
        TFESPECIALIDAD.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        TFESPECIALIDAD.setForeground(new java.awt.Color(255, 255, 255));

        BOTONCERRAR.setBackground(new java.awt.Color(167, 9, 9));
        BOTONCERRAR.setFont(new java.awt.Font("sansserif", 1, 15)); // NOI18N
        BOTONCERRAR.setForeground(new java.awt.Color(255, 255, 255));
        BOTONCERRAR.setText("CERRAR");
        BOTONCERRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTONCERRARActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 0, 13)); // NOI18N
        jLabel10.setText("TIEMPO DE SERVICIO");

        TFTIEMPOSERVICIO.setBackground(new java.awt.Color(0, 0, 51));
        TFTIEMPOSERVICIO.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(446, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(BOTONCERRAR, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(TFNOMBRES, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                                            .addComponent(TFCODIGO, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TFDIRECCION)
                                            .addComponent(TFCORREO)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(TFTIEMPOSERVICIO)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel3))
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TFCELULAR, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                                    .addComponent(TFAPELLIDOS)
                                    .addComponent(TFSEXO)
                                    .addComponent(TFESPECIALIDAD))))
                        .addGap(27, 27, 27))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(TFCODIGO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(TFCELULAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(TFNOMBRES, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(TFAPELLIDOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(TFDIRECCION, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(TFSEXO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(TFCORREO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(TFESPECIALIDAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(TFTIEMPOSERVICIO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5)
                .addComponent(BOTONCERRAR)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BOTONCERRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTONCERRARActionPerformed
       this.dispose();
    }//GEN-LAST:event_BOTONCERRARActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BOTONCERRAR;
    private javax.swing.JTextField TFAPELLIDOS;
    private javax.swing.JTextField TFCELULAR;
    private javax.swing.JTextField TFCODIGO;
    private javax.swing.JTextField TFCORREO;
    private javax.swing.JTextField TFDIRECCION;
    private javax.swing.JTextField TFESPECIALIDAD;
    private javax.swing.JTextField TFNOMBRES;
    private javax.swing.JTextField TFSEXO;
    private javax.swing.JTextField TFTIEMPOSERVICIO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
